// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQzb7Jo_QpAxLl6fe2lf3z1YSOIUTaVAk',
    appId: '1:53492111582:web:d2a901734573c4e91b0a4f',
    messagingSenderId: '53492111582',
    projectId: 'ingilizce-e826d',
    authDomain: 'ingilizce-e826d.firebaseapp.com',
    storageBucket: 'ingilizce-e826d.firebasestorage.app',
    measurementId: 'G-DV1S4FXQS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxaYGFhx2f9FX3htIcMyQlP_2oxBmzyo',
    appId: '1:53492111582:android:405cc48916d455481b0a4f',
    messagingSenderId: '53492111582',
    projectId: 'ingilizce-e826d',
    storageBucket: 'ingilizce-e826d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwwXUIAjIdCdzTvhM4v-UppAGLoyYM4L8',
    appId: '1:53492111582:ios:bb192a63f6a523611b0a4f',
    messagingSenderId: '53492111582',
    projectId: 'ingilizce-e826d',
    storageBucket: 'ingilizce-e826d.firebasestorage.app',
    iosBundleId: 'com.ufukkoca.LearningEnglishVocabulary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwwXUIAjIdCdzTvhM4v-UppAGLoyYM4L8',
    appId: '1:53492111582:ios:bb192a63f6a523611b0a4f',
    messagingSenderId: '53492111582',
    projectId: 'ingilizce-e826d',
    storageBucket: 'ingilizce-e826d.firebasestorage.app',
    iosBundleId: 'com.example.ingilizce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQzb7Jo_QpAxLl6fe2lf3z1YSOIUTaVAk',
    appId: '1:53492111582:web:9badb9402cfc6bc81b0a4f',
    messagingSenderId: '53492111582',
    projectId: 'ingilizce-e826d',
    authDomain: 'ingilizce-e826d.firebaseapp.com',
    storageBucket: 'ingilizce-e826d.firebasestorage.app',
    measurementId: 'G-RJXELRH11L',
  );
}
